[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ronkey = {git = "https://github.com/jgcardelus/ronkey", rev = "2f22650"}
rocket = "0.5.1"
ws = { package = "rocket_ws", version = "0.1.1" }
